### ISSUE TITLE
Reorganize AguaClara_Interactive_Tutorial.md

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aguaclara_tutorial#28]
The current interactive tutorial is quite intimidating and long. It should be broken up into different files for teaching Markdown, Python, and Git, and should be well integrated with the tutorials in the wiki.

For example, a wiki tutorial would explain a concept, then tell the user to "Go to section XYZ in the interactive tutorial file to try this for yourself." Afterwards, the interactive tutorial would tell the user to "Return to section ABC in the tutorial wiki.

## TODO
- [ ] Split up the interactive tutorial into 3-4 different sections
- [ ] Add references between the tutorial and the wiki (To be done as tutorials are written)

(Originally from issue #19)

**Comment by IanCullings** [comment]
We should also add a section on how to use the aguaclara_research functions.  This should include:
- [ ] How to install aguaclara_research and import the function
- [ ] How to look up a function and understand what it does, what the inputs are, etc.
- [ ] An example research problem that you need to call a function to solve
- [ ] How to make python graphs of your data
- [ ] A continuation of the previous problem where you plot the data using python
- [ ] A link to the aguaclara_research wiki and functions for reference

@HannahSi once you feel comfortable with the state of aguaclara_research, can you write this section and have one of us review it?
